### ISSUE TITLE
Tuning the parameter, gamma, using the function L0Learn.cvfit

### ISSUE THREAD

**Issue by vtshen** [hazimehh/L0Learn#32]
After running the function L0Learn.cvfit, there are values equal to 0 in the results from cvfit$cvMeans, which is confusing, because the error should always be greater than 0.

```
> cvfit$cvMeans[1,1]
[[1]]
 [1] 39.474119 39.473877 39.473055 39.472827 39.472379 39.472067 39.471837 39.471278 39.471120
[10] 39.470902 39.470746 39.470734 39.470730 39.470731 39.470726 39.470726 39.470725 39.470725
[19] 39.470725 39.470725 39.470718 39.470717 39.470710 39.470712 39.470720 39.470723 39.470721
[28] 39.470721 39.470716 39.470718 39.470718 39.470718 39.470715 39.470713 39.470714 39.470715
[37] 39.470717 39.470714 39.470712 39.470711 39.470711 39.470710 39.470707 31.497491 23.998097
[46] 16.108749 16.108748  8.329246  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
[55]  0.000000  0.000000  0.000000  0.000000  0.000000
```

The code used to generate the above results
```R
# simulate x, y
     n = 5000
      p = 1000
      s = 10
      rho = 0.35
      x = matrix(rnorm(n*p),n,p)
      inds = 1:p
      Sigma = rho^abs(outer(inds, inds, "-"))
      obj = svd(Sigma)
      Sigma.half = obj$u %*% (sqrt(diag(obj$d))) %*% t(obj$v)
      x = x %*% Sigma.half
      beta = rep(0,p)
      beta[1:s] = 1
      vmu = as.numeric(t(beta) %*% Sigma %*% beta)
      sigma = sqrt(vmu)
      y = as.numeric(x %*% beta + rnorm(n)*sigma)
# set range of gamma
    xty = base::crossprod(x,y)
    gamma_max = max(abs(xty)) # another choice based on proof is sqrt(sum((xty)^2))
    gamma_min = 1e-5 * gamma_max
    nGamma = 50
# run the function
    cvfit = L0Learn::L0Learn.cvfit(x, y, nFolds=5, seed=1, penalty="L0L2", nGamma=nGamma, gammaMin=gamma_min, gammaMax=gamma_max, maxSuppSize=100)
    cvfit$cvMeans[1,1]
```

**Comment by hazimehh** [comment]
Thank you very much for reporting this! TLDR: This issue occurs when maxSuppSize is set to a small value. Increasing maxSuppSize fixes the issue (e.g., maxSuppSize=500 in your example works). I will update the package later today to fix this. 

Details (for myself and future developers): The method `cvfit` works by first fitting a model on the full data  (X,y) using the `fit` method, where it obtains a Lambda grid for every gamma. Then, the folds in cross-validation are fitted over the fixed Lambda grids obtained initially using the `fit` method. The problem is that when maxSuppSize is small, some solutions obtained during the fold fitting (especially at the end of the path) might exceed maxSuppSize, and thus these solutions are ignored from the path and from the CV error calculations (which is leading to the zeros). One easy fix is to ignore the maxSuppSize parameter for the fold fitting during CV (but still respect maxSuppSize when fitting the full model).

**Comment by hazimehh** [comment]
The latest version of L0Learn (1.0.8) fixes the problem and is now available on CRAN.
